### ISSUE TITLE
delete_row.cpp does not work

### ISSUE THREAD

**Issue by orestotel** [orestotel/hacktoberfest-ProjectCPlusPlus#7]
Given the dimensions of the matrix, delete line, where the sum of elements is the lowest. Return the highest element of the matrix.

The issue is that I need help with heap memory in C++. The array lines don't get deleted or reassigned different values for some reason. Assistance appreciated.

**Comment by orestotel** [comment]
[https://github.com/orestotel/ProjectCPlusPlus/blob/master/delete_row.cpp](url)

**Comment by Tai-Min** [comment]
By "delete" do you mean set value to 0? That's what I assumed from the code.

**Comment by orestotel** [comment]
@Tai-Min since the heap memory method didn't work, I tried to set the value to 0 instead of deleting, but that didn't work either yet. "Delete[]" method is prioritized over the "set value to 0 method". 
__The main task is to actually to delete the line with the lowest element.__

**Comment by orestotel** [comment]
Thank you, @Tai-Min 
Looking forward to your contributions to this repository in the future.
